### ISSUE TITLE
Question Please =)

### ISSUE THREAD

**Issue by pingou2712** [virus2500/blocklist-with-ipset#12]
Hi, 
(sorry for my english, i'm french)

Hello,
I'm trying to block bad ip on my new server and i see your job =)
Why did you stop working on your job?
Now, is there something better? with nftables? What method are you using now to fight against bad ip.

Thank you very much in advance for your response.
Vincent L.

**Comment by virus2500** [comment]
Hi,

well at first it was mainly a time issue with work and then other things took precedence.

The thing is my setup by now changed so much that i don't use it all anymore. I don't really use any solution at the moment because my biggest annoyence (people trying to break in via ssh) is not present anymore because i don't give access to my ssh publicly anymore (vpn is required to get in)

However, Kubax did make a fork back in the day with nftables. So maybe this is interesting for you?
https://github.com/kubax/blocklist-with-nftables

best regards
Michael

**Comment by pingou2712** [comment]
Hi,

Thank you very very much for your answer.

I saw indeed the fork of kubax just after. I think to take this solution because i have other intrusion (other ssh) on my server....

Just one a little question: I haven't tested sets with nftables yet ... the solution does not take too long time on a big list like https://lists.blocklist.de/lists/all.txt? (before the line "ct state related,established  accept"). Because test all ip of the list for all request, it scares me.... (ahahah i don't know if you understand lol)

Really, thanks again...
best regards
Vincent L.

**Comment by virus2500** [comment]
To be honest, i haven't tested the nftables implementation but i suggest to just give it a try :)
At least in my implementation, after an inital import, which of course took a little bit due to the size of the list, it just compared the lists and only applied the necessary changes thus improving the time it took to apply necessary changes.

best regards
Michael

**Comment by pingou2712** [comment]
Thank you very much for all of your responses.

best regards
Vincent L.
